# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

sonar.projectKey=Harjotsingh2001_jupyterlab
sonar.organization=harjotsingh2001

# Source code
sonar.sources=packages

# Exclusions
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.github/**

# JavaScript / TypeScript
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Python coverage (optional)
sonar.python.coverage.reportPaths=coverage.xml

# Encoding
sonar.sourceEncoding=UTF-8







